#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable is not set."
    exit 1
fi

output_file="${PYFILE}c"

python3 -m compileall "$PYFILE"

if [ $? -ne 0 ]; then
    echo "Error: Compilation failed."
    exit 1
fi

mv "__pycache__/${PYFILE%.*}.cpython-*.pyc" "$output_file"

rm -rf "__pycache__"

echo "Compilation completed. Output filename: $output_file"
